### ISSUE TITLE
Will this continue to be updated with the official docs?

### ISSUE THREAD

**Issue by GrittyChen** [unknownue/PyTorch.docs#1]
This is a good job, thank you, will this continue to be updated with the official docs?

**Comment by unknownue** [comment]
Yes, I plan to update the docs when the major/minor version increases(e.g. from v1.3.0 to v1.4.0).
You also can create new issue to request docs update.

Once the building pipeline was set at the first time, updating the docs version would not bring much pain.

**Comment by GrittyChen** [comment]
@unknownue That is great, thanks!
