### ISSUE TITLE
pdf or markdown

### ISSUE THREAD

**Issue by XiaoJiNu** [unknownue/PyTorch.docs#2]
Hi, can you convert this docment to pdf or markdown format?

**Comment by unknownue** [comment]
Which document are you refer to? pytorch or numpy?
I don't know what is the preferred markdown format you mean, but the Sphinx build system does provide a pdf option.
Please explain more detail about you request.

**Comment by XiaoJiNu** [comment]
@unknownue I want get pdf or markdow file of pytorch，because html is difficult to make note.

**Comment by unknownue** [comment]
Generate markdown seems to be impractical, as the docs is generated by inline code comment, what is not intended to generate for markdown.
I try the latexpdf option provided by Sphinx. It require many dependencies of latex(including the `texlive-latex-extra`, `texlive-formats-extra`). Even though all latex dependencies have been installed, lots of warning and error appear.
And the following error has stopped me to proceed:
```
! Package inputenc Error: Unicode character ✘ (U+2718)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.47863 \end{tabulary}
```
This seems the same issue of [this](https://github.com/sphinx-doc/sphinx/issues/4136). I can't find any easy-fix method without modifying the pytorch code base, so I finally gave up.
If you find any solution, I would give more try. But now, I have no idea to continue. Obviously, the pytorch team does not mantain a pdf docs option.

**Comment by XiaoJiNu** [comment]
@ unknownue Thank you very much, I got it.
