### ISSUE TITLE
Issues building pytorch docs

### ISSUE THREAD

**Issue by Asciotti** [unknownue/PyTorch.docs#3]
Hey,

I was building the pytorch docs from the docker images and kept running into the issue below after building the image then running the `docker run ...` command.

```
make: *** No rule to make target `html'.  Stop.
```

I would expect this to happen if the `docker run ...` command placed me in the incorrect directory or the make file didn't have an html creation path. 

I tried to see where one ends up by running

```
docker run -it \
    -v $(pwd)/build/torch:/root/dev/pytorch/docs/build \
    -w /root/dev/pytorch/docs/ \
    pytorch.docs \
    /bin/bash
```

which does appear to put us in the correct directory with the correct files.
![image](https://user-images.githubusercontent.com/25936220/92313244-9826c800-ef97-11ea-9b5b-b7a4948bd805.png)

I even manually ran `pip3 install -r requirements.txt --no-cache-dir` and then `make html` inside and it works that way.

Any ideas on how to track this down?

Docker version `19.03.5, build 633a0ea`. On MacOs Mojave 10.14.6.

**Comment by unknownue** [comment]
I don't know the exact reason, but I think there may be some environment variables had not been update in **non-interactive** docker container.
Try the following command, it works on my machine:
```shell
$ docker run --rm \
    -v $(pwd)/build/torch:/root/dev/pytorch/docs/build \
    -w /root/dev/pytorch/docs/ \
    pytorch.docs \
    bash -c "pip3 install -r requirements.txt --no-cache-dir && make html"
```

PR is welcome.

**Comment by Asciotti** [comment]
That seems to have worked. That is strange. I did note that the docker image for pytorch was much different than the others. I assume you went through the pytorch building process as the original idea and then through the others later (given the name of the repo 😄 ). I will see if I find some time to make the pytorch process similar to the others.

Happy to make a PR for the immediate, though I am unsure if it is just me or others will run into the issue. 

I need to build some other docs, interested in those in here as well? Probably pandas, tensorflow, maybe a few others.
