### ISSUE TITLE
scikit-learn帮助文档图片不全

### ISSUE THREAD

**Issue by jue-jue-zi** [unknownue/PyTorch.docs#4]
scikit-learn中很多图片无法正常加载出来

**Comment by unknownue** [comment]
在 https://matplotlib.org 也有一些图片本身就是没有的，请你举出更具体的例子

**Comment by jue-jue-zi** [comment]
是scikit-learn的离线文档的tu'pian图片有缺失，详见下图：
![offline](https://user-images.githubusercontent.com/26075785/98455523-c6e63800-21ac-11eb-9309-9fa3d1054d35.PNG)
![online](https://user-images.githubusercontent.com/26075785/98455525-c9489200-21ac-11eb-9e1f-9d25d379bf25.PNG)

**Comment by unknownue** [comment]
我重新build了一次，发布到[这里](https://github.com/unknownue/PyTorch.docs/releases/tag/v1.7.1) ，build的过程还是有些错误处理不了，但大部分的图片应该都有了。如果你还有问题，重新打开这个issue.
